import type { Metadata } from 'next';
import '@/styles/globals.css';
import  SmoothScroll  from '@/hooks/useSmoothScroll';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SmoothScroll>
      <html lang="ko">
        <body className="bg-red">
          <main className="bg-red">{children}</main>
        </body>
      </html>
    </SmoothScroll>
  );
}
